
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package analizadores;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int LLAIZQ = 8;
  public static final int LLADER = 9;
  public static final int GNAR = 4;
  public static final int DIAG = 25;
  public static final int CONJUNTO = 26;
  public static final int UNOMAS = 12;
  public static final int ALFA = 23;
  public static final int CERUNO = 13;
  public static final int CONCAT = 10;
  public static final int UPPER = 18;
  public static final int CARACTER = 28;
  public static final int SEPARADOR = 15;
  public static final int COMA = 7;
  public static final int LOWER = 17;
  public static final int EOF = 0;
  public static final int ASI = 3;
  public static final int DISYUNCION = 14;
  public static final int COMILLADOBLE = 24;
  public static final int LEXEM = 21;
  public static final int error = 1;
  public static final int IDENTIFICADOR = 22;
  public static final int DPUNTO = 2;
  public static final int CEROMAS = 11;
  public static final int LOPPER = 19;
  public static final int ASCII = 20;
  public static final int SALTO = 27;
  public static final int ENTERO = 16;
  public static final int RANGO = 5;
  public static final int PTCOMA = 6;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "DPUNTO",
  "ASI",
  "GNAR",
  "RANGO",
  "PTCOMA",
  "COMA",
  "LLAIZQ",
  "LLADER",
  "CONCAT",
  "CEROMAS",
  "UNOMAS",
  "CERUNO",
  "DISYUNCION",
  "SEPARADOR",
  "ENTERO",
  "LOWER",
  "UPPER",
  "LOPPER",
  "ASCII",
  "LEXEM",
  "IDENTIFICADOR",
  "ALFA",
  "COMILLADOBLE",
  "DIAG",
  "CONJUNTO",
  "SALTO",
  "CARACTER"
  };
}

