
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package analizadores;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int LLAIZQ = 7;
  public static final int LLADER = 8;
  public static final int CONJUNTO = 20;
  public static final int CONCAT = 9;
  public static final int UPPER = 15;
  public static final int ASIGNAR = 3;
  public static final int SEPARADOR = 12;
  public static final int COMA = 6;
  public static final int LOWER = 14;
  public static final int EOF = 0;
  public static final int DISYUNCION = 11;
  public static final int COMILLADOBLE = 19;
  public static final int LEXEM = 17;
  public static final int error = 1;
  public static final int IDENTIFICADOR = 18;
  public static final int DPUNTO = 2;
  public static final int CEROMAS = 10;
  public static final int LOPPER = 16;
  public static final int ENTERO = 13;
  public static final int RANGO = 4;
  public static final int PTCOMA = 5;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "DPUNTO",
  "ASIGNAR",
  "RANGO",
  "PTCOMA",
  "COMA",
  "LLAIZQ",
  "LLADER",
  "CONCAT",
  "CEROMAS",
  "DISYUNCION",
  "SEPARADOR",
  "ENTERO",
  "LOWER",
  "UPPER",
  "LOPPER",
  "LEXEM",
  "IDENTIFICADOR",
  "COMILLADOBLE",
  "CONJUNTO"
  };
}

